<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="MIDHUN MADHU">

<title>Customer Segmentation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Segmentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="Segmentation_files/libs/quarto-html/quarto.js"></script>
<script src="Segmentation_files/libs/quarto-html/popper.min.js"></script>
<script src="Segmentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Segmentation_files/libs/quarto-html/anchor.min.js"></script>
<link href="Segmentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Segmentation_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Segmentation_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Segmentation_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Segmentation_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Customer Segmentation</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>MIDHUN MADHU </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="market-segmentation-report" class="level1">
<h1><u>Market Segmentation Report</u></h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 7
     Age Female Income Married Children  Loan Mortgage
   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
 1    48      1 17546        0        1     0        0
 2    40      0 30085.       1        3     1        1
 3    51      1 16575.       1        0     1        0
 4    23      1 20375.       1        3     0        0
 5    57      1 50576.       1        0     0        0
 6    57      1 37870.       1        2     0        0
 7    22      0  8877.       0        0     0        0
 8    58      0 24947.       1        0     1        0
 9    37      1 25304.       1        2     1        0
10    54      0 24212.       1        2     1        0
# ℹ 20 more rows</code></pre>
</div>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1.Introduction</h2>
<p><strong>The KTC Company</strong> would like to segment their customers based on their characteristics.The company has information regarding the customers for segmentation.The company would like to group customers as per their requirements and characteristics based on the data the entity have regarding customers.</p>
</section>
<section id="descriptive-mining" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-mining">2.Descriptive Mining</h2>
<section id="exploratory-data-analysis-data-exploration" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis-data-exploration">2.1 Exploratory Data Analysis (Data Exploration)</h3>
<p>We have information regarding 30 customers of KTC Company.The Company has details of their age,income,gender,marital status,dependents(number of children),financial status(car loan,mortgage loan).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Data frame:crs$dataset[, c(crs$input, crs$risk, crs$target)]    30 observations and 7 variables    Maximum # NAs:0

         Storage
Age       double
Female    double
Income    double
Married   double
Children  double
Loan      double
Mortgage  double</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age            Female           Income         Married   
 Min.   :22.00   Min.   :0.0000   Min.   : 8877   Min.   :0.0  
 1st Qu.:37.25   1st Qu.:0.0000   1st Qu.:18166   1st Qu.:1.0  
 Median :47.00   Median :1.0000   Median :24241   Median :1.0  
 Mean   :45.97   Mean   :0.5667   Mean   :28012   Mean   :0.8  
 3rd Qu.:56.75   3rd Qu.:1.0000   3rd Qu.:35923   3rd Qu.:1.0  
 Max.   :66.00   Max.   :1.0000   Max.   :59804   Max.   :1.0  
    Children           Loan           Mortgage  
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0  
 Median :0.5000   Median :0.0000   Median :0.0  
 Mean   :0.9333   Mean   :0.4333   Mean   :0.4  
 3rd Qu.:2.0000   3rd Qu.:1.0000   3rd Qu.:1.0  
 Max.   :3.0000   Max.   :1.0000   Max.   :1.0  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>crs$dataset[, c(crs$input, crs$risk, crs$target)] 

 7  Variables      30  Observations
--------------------------------------------------------------------------------
Age 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
      30        0       23    0.998    45.97     46.5    15.12    22.45 
     .10      .25      .50      .75      .90      .95 
   26.60    37.25    47.00    56.75    61.10    64.20 

lowest : 22 23 27 31 36, highest: 57 58 61 62 66
--------------------------------------------------------------------------------
Female 
       n  missing distinct     Info      Sum     Mean 
      30        0        2    0.737       17   0.5667 

--------------------------------------------------------------------------------
Income 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
      30        0       30        1    28012    25590    14919    13945 
     .10      .25      .50      .75      .90      .95 
   15716    18166    24241    35923    51039    56676 

lowest : 8877.07 12640.3 15538.8 15735.8 16497.3
highest: 41034   50576.3 55204.7 57880.7 59803.9
--------------------------------------------------------------------------------
Married 
       n  missing distinct     Info      Sum     Mean 
      30        0        2    0.481       24      0.8 

--------------------------------------------------------------------------------
Children 
       n  missing distinct     Info     Mean  pMedian      Gmd 
      30        0        4    0.858   0.9333        1    1.163 
                                  
Value          0     1     2     3
Frequency     15     5     7     3
Proportion 0.500 0.167 0.233 0.100

For the frequency table, variable is rounded to the nearest 0
--------------------------------------------------------------------------------
Loan 
       n  missing distinct     Info      Sum     Mean 
      30        0        2    0.737       13   0.4333 

--------------------------------------------------------------------------------
Mortgage 
       n  missing distinct     Info      Sum     Mean 
      30        0        2    0.721       12      0.4 

--------------------------------------------------------------------------------</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> /\     /\
{  `---'  }
{  O   O  }
==&gt;  V &lt;==  No need for mice. This data set is completely observed.
 \  \|/  /
  `-----'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Age Female Income Married Children Loan Mortgage  
30   1      1      1       1        1    1        1 0
     0      0      0       0        0    0        0 0</code></pre>
</div>
</div>
<p>The mice function confirms that the data has no missing values.</p>
<section id="age" class="level4">
<h4 class="anchored" data-anchor-id="age">2.1.1 Age</h4>
<p>After exploring the data,we can conclude that the minimum age of customers is 22 and maximum age is 66.The average age of customers is 45.97.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The box plot shows that there is no outliers or extreme values in the data.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histogram shows that most people are in the age range between 40s and 60s.It means that it is a kind of bi-model figure.</p>
</section>
<section id="income" class="level4">
<h4 class="anchored" data-anchor-id="income">2.1.2 Income</h4>
<p>After data exploration the company came to conclusion that that the income range of customers is between ₹8,877 and ₹59,804.The average value being ₹28,012 and median being ₹24,241.</p>
<p>Right-skewed (mean &gt; median)</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Box Plot Interpretation</em></strong></p>
<p>The box plot for income shows that there are no extreme values.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Histogram Interpretation</em></strong></p>
<p>The histogram for income is positively skewed (skewed to the right) which shows that most people have low income and only very small number of people have very high income</p>
</section>
<section id="gender" class="level4">
<h4 class="anchored" data-anchor-id="gender">2.1.3 Gender</h4>
<p>The data provides the information that majority (56.7%) are females as the mean is 0.5667 and median is 1.</p>
</section>
<section id="marital-status" class="level4">
<h4 class="anchored" data-anchor-id="marital-status">2.1.4 Marital Status</h4>
<p>The data shows that 80% of the people are married as the mean is 0.8 and the remaining 20% are unmarried.</p>
</section>
<section id="number-of-children" class="level4">
<h4 class="anchored" data-anchor-id="number-of-children">2.1.5 Number of children</h4>
<p>The data depicts that the maximum number of children for the customers in the given set is 3 per individual.However,on average there is only one child per individual as the mean is (0.933).As the median is 0.5,most customers have 0 child.</p>
</section>
<section id="loan-status" class="level4">
<h4 class="anchored" data-anchor-id="loan-status">2.1.6 Loan Status</h4>
<p>Out of the total customers,nearly 44% has loan liability.Majority of the customers have no loan as the median is 0.</p>
</section>
<section id="mortgage" class="level4">
<h4 class="anchored" data-anchor-id="mortgage">2.1.7 Mortgage</h4>
<p>The mortgage status is almost similar to loan status as only 40% have a mortgage as mean is 0.4 and majority does not have mortgage as median being 0.</p>
</section>
</section>
</section>
<section id="segmentation-using-clustering" class="level2">
<h2 class="anchored" data-anchor-id="segmentation-using-clustering">3. <strong>Segmentation using Clustering</strong></h2>
<p><strong>Clustering</strong> is a method of grouping the observations based on their similarities.We use distance measures for assessing the dissimilarity among the observations.</p>
<section id="hierarchical-clustering" class="level3">
<h3 class="anchored" data-anchor-id="hierarchical-clustering">3.1 Hierarchical Clustering</h3>
<p><strong>Hierarchical Clustering</strong> is an algorithm that builds a hierarchy (tree) of clusters, without pre-specifying the number of clusters. It can be visualized using a <strong>dendrogram</strong>, which shows how clusters are merged or split over time.</p>
<p><strong>Hierarchical clustering</strong> is performed with number of clusters as 10 and <strong>dendrogram</strong> is created</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The dendrogram shows the agglomeration at different ages.After the hierarchical clustering is done,k means clustering is done with number of clusters set to 5 and later to 3 clusters.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="k-means-clustering" class="level3">
<h3 class="anchored" data-anchor-id="k-means-clustering">3.2 K-Means Clustering</h3>
<p><strong>K-means</strong> is an <strong>unsupervised machine learning algorithm</strong> used to partition a dataset into <strong>K distinct, non-overlapping clusters</strong> based on similarity.It organizes observations into similar groups.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "9 9 3 2 7"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age    Female    Income   Married  Children      Loan  Mortgage 
0.5446970 0.5666667 0.3757313 0.8000000 0.3111111 0.4333333 0.4000000 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        Age    Female     Income   Married  Children      Loan Mortgage
1 0.5303030 0.5555556 0.40043981 1.0000000 0.2592593 0.4444444        1
2 0.6111111 1.0000000 0.42584074 0.8888889 0.3333333 0.2222222        0
3 0.3939394 1.0000000 0.29405253 0.0000000 0.3333333 1.0000000        1
4 0.0000000 0.0000000 0.03694742 0.0000000 0.3333333 0.5000000        0
5 0.6980519 0.0000000 0.41133723 1.0000000 0.3333333 0.4285714        0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.4813274 5.0793648 0.8695460 0.7249524 3.1697907</code></pre>
</div>
</div>
<p>As the diagram shows too much overlapping between the variables,it is decided to change the cluster size to 3.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "9 9 3 2 7"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age    Female    Income   Married  Children      Loan  Mortgage 
0.5446970 0.5666667 0.3757313 0.8000000 0.3111111 0.4333333 0.4000000 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        Age    Female     Income   Married  Children      Loan Mortgage
1 0.5303030 0.5555556 0.40043981 1.0000000 0.2592593 0.4444444        1
2 0.6111111 1.0000000 0.42584074 0.8888889 0.3333333 0.2222222        0
3 0.3939394 1.0000000 0.29405253 0.0000000 0.3333333 1.0000000        1
4 0.0000000 0.0000000 0.03694742 0.0000000 0.3333333 0.5000000        0
5 0.6980519 0.0000000 0.41133723 1.0000000 0.3333333 0.4285714        0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.4813274 5.0793648 0.8695460 0.7249524 3.1697907</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As there is many overlapping when clustering is done using 5 clusters,the elbow diagram is prepared to know the optimal numbers of clusters to be used for the segmentation.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1 2 2 2 3 3 1 3 2 2 3 1 2 3 2 2 2 3 3 2 3 2 3 1 1 3 2 2 1 3</code></pre>
</div>
</div>
<p>After preparing the elbow plot the elbow or the curve is visible in the 3rd point,which means that the optimal cluster size is 3.So, using the K means clustering,the discriminant plot is prepared with 3 clusters.It is found from the graph that there is less overlapping compared to previous diagram.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "9 15 6"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age    Female    Income   Married  Children      Loan  Mortgage 
0.5446970 0.5666667 0.3757313 0.8000000 0.3111111 0.4333333 0.4000000 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        Age    Female    Income Married  Children      Loan Mortgage
1 0.5303030 0.5555556 0.4004398       1 0.2592593 0.4444444      1.0
2 0.6530303 0.5333333 0.4361136       1 0.3333333 0.3333333      0.0
3 0.2954545 0.6666667 0.1877126       0 0.3333333 0.6666667      0.5</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  6.481327 11.117786  5.631834</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Segmentation_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  cluster_id      Age    Female   Income Married  Children      Loan  Mortgage
1          1 35.00000 0.6666667 18436.68       0 1.0000000 0.6666667 0.5000000
2          2 40.38462 0.5384615 20906.03       1 1.2307692 0.4615385 0.4615385
3          3 58.54545 0.5454545 41632.52       1 0.5454545 0.2727273 0.2727273</code></pre>
</div>
</div>
<p>This is the k means clustering with 3 clusters and discriminant plot is prepared.We can find that the overlapping is less with 3 clusters compared to clustering done with 5 clusters.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>